### ISSUE TITLE
DOCS :git action을 이용한 배포 자동화

### ISSUE THREAD

**Issue by kwanyung** [moodCatcherProject/Back-End#71]
https://github.com/appleboy/ssh-action

저희가 이용한 방법은 이 애플보이라는 닉네임을 쓰는 사람의 git을 참조한 것 입니다.

git action은 레파지토리에 어떤 이벤트가 생길 때 마다 특정한 작업을 실행해주는 일을 하는데요. 

이를 이용한다면 push를 할 때나 PR을 할 경우 테스트 코드를 실행 한다거나 프리티어를 적용한다거나 여러 일들을 자동화 시킬 수 있게 됩니다.

저희가 시도한 것은 그 중에서도 자동으로 우분투에 있는 배포서버를 업데이트 하기 위한 auto CICD였습니다. 

일요일 모두가 쉴 때 프론트, 백 모두 자동 배포화를 성공해서 너무 기쁘게 생각하고 있습니다.

하지만 과정이 순탄치 않았던 만큼 과정은 어땠는지, 왜 오류를 만났는지 기록해 보겠습니다.

![시크릿](https://user-images.githubusercontent.com/71562311/188525013-ef79a9e6-d48b-4a22-87ab-984525348bbe.PNG)

Secrets는 저희가 흔히 쓰는 환경변수 .env와 비슷한 기능을 하는 친구들입니다,

배포한 서버의 secretKey라던가 s3, jwt를 sign할 때 사용하는 비밀키 등등 관리자가 아닌 다른 사람에게 넘겨줄 수 없는 정보들을 저장하는 공간입니다.

처음 Dependabot에 내용을 넣었으나 계속 action에서 에러가 나는 것을 확인할 수 있었죠.

분명 비밀키를 넣어주었는데 비밀키가 필요하다던가... 상식적으로 Secrets에 있는 내용을 잘 불러온다면 있을 수 없는 에러였습니다.

Dependabot는 저장소의 패키지 및 어플의 최신 릴리즈를 유지할 수 있도록 자동으로 업데이트 시켜주는 깃허브 봇 입니다.

action에 사용하려던 의도와는 거리가 있었지 싶네요. 이후 action으로 내용들을 옮기니 최소한 Secrets에 있는 내용을 읽어오는 데 까지는 성공했습니다.

```
name: Node.js CI

on:
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
            - name: Deploy
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.REMOTE_IP }}
                  username: ${{ secrets.SSH_ID }}
                  key: ${{ secrets.SSH_KEY }}
                  port: 22
                  script: |
                      cd Back-End
                      git pull origin main
                      npm ci
                      sudo pm2 stop 0
                      sudo pm2 start src/server.js
```
action의 문법?

on : 작업을 발생시킬 이벤트 지정 (main에 PR을 한다거나...)
jobs : 무슨 작업을 할 지 환경과 작업 과정을 지정

appleboy라는 사람의 파일을 이용하니 코드의 내용은 그리 길지 않았으나 host에는 어떤 내용이 들어갈지 username에는 어떤 내용이 들어갈지 알아가는 과정이 필요했습니다. ssh에 대해 이해가 부족함을 느끼는 순간이였습니다.

결과부터 말씀 드리자면 

host에는 ec2에서 사용하고 있는 인스턴스의 공개 IP

username 에는 ssh -i 비밀키 id@ip 이 부분에서 id를 넣으면 됩니다. 이 username이 무엇을 의미하는지 찾아보느라 시간이 오래 걸렸습니다.

aws에 들어가서 찾아보기도 하고 구글링 해도 관련 정보가 나오지 않았습니다. 아마 웹개발 종합반 때 넌지시 들었을 텐데 기억이 날리가 없더라구요.

key 부분에는 pem키, 비밀키를 넣어주면 됩니다. aws 계정을 만들 때 비밀키를 가지는 파일을 로컬컴퓨터에 저장하게 되는데 그 값을 넣어주면 됩니다. start~ end 라고 ------- 로 이루어진 구분선이 있는데 이런 선까지 모두 넣어주어야 합니다.

port부분은 포트번호를 넣어주는데 기본적으로 22번을 많이 쓴다고 해서 넣어두었습니다. 
=> Secrets에 보관하는게 좋은 방법이라고 하네요. (수정하겠습니다.)

이후 script 부분에는 우분투 서버에서 실행할 명령어를 입력합니다.

서버의 파일로 들어가고, git pull 을 받고.. 하는 과정을 거치게 됩니다.

처음 자동 배포가 어려웠던 것은 

1. git action의 문법이 처음보는 문법이라 익숙하지 않았음. 그리고 너무 어렵게 생각했음.
2. username에 어떤 값이 들어가야 할지 몰랐고 공개 IP에도 ec2 인스턴스에 있는 IP를 넣는게 맞는지 등.. 테스트를 해보는 방법을 모르니 확신이 서지 않았음.

하지만 git action을 한 줄 씩 바꿔가며 시도한 결과 생각보다 너무 쉬운 값들이 들어가서 놀랐습니다.

민망할 정도로요!

이제 git action활용을 알았으니 테스트 코드 등 더 활용할 방안을 찾아봐야겠습니다!
